spring:
  cloud:
    gateway:
      routes:
        - id: msvc-courses
          uri: lb://msvc-courses
          predicates:
            - Path=/api/msvc-courses/**
          filters:
            - StripPrefix=2
        - id: msvc-users
          uri: lb://msvc-users
          predicates:
            - Path=/api/msvc-users/**
          filters:
            - StripPrefix=2