apiVersion: v1
kind: PersistentVolume
metadata:
  name:  msvc-courses-db-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/mysqlcourses
    type: DirectoryOrCreate


