apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  msvc-users-db-pvc
spec:
  volumeName: msvc-users-db-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi