apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  msvc-courses-db-pvc
spec:
  volumeName: msvc-courses-db-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi